######################################################################
##
## Filename: s6base_tb.udo
## Created on: Tue Oct 25 18:00:09 GMT Daylight Time 2016
##
## Auto generated by Project Navigator for Post-Behavioral Simulation
##
## You may want to edit this file to control your simulation.
##
######################################################################
