name: ALUX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Iverilog
      run: sudo apt-get install iverilog
      
    - name: Make List
      run: cd Project3 && make list
      
    - name: Make Module
      run: cd Project3 && make module
      