name: Lab2 Part1

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Iverilog
      run: sudo apt-get install iverilog
      
    - name: Make List
      run: cd 2022/Lab2/Part1 && make   
