name: Makefile CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Iverilog
      run: sudo apt-get install iverilog
      
    - name: Make List
      run: cd Project1 && make list
      
    - name: Make Module
      run: cd Project1 && make module
      
    - name: Make Compile check
      run: cd Project1 && make compile
     
    - name: Simulate 
      run: cd Project1 && make simulate
